spring:
  profiles:
    group:
      "local": "local, common, oauth"
    default: local
---
# common

spring:
  config:
    activate:
      on-profile: "common"

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false  #기본 true, 개발시에는 false로 캐싱 없에야 편함
  mvc:
    static-path-pattern: /static/** # static 파일 경로 설정


server:
  shutdown: graceful
  port: 8010

---
# local
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/neighborhooddb
      username: master
      password: 1234
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true  # 쿼리 출력시 포맷 정렬
        use_sql_comments: true  # 주석 출력
        show_sql: true  # JPA 출력시 쿼리 출력
        jdbc:
          time_zone: UTC

logging:
  config: classpath:log4j2.xml
