spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 512417503371-1e9a5bfkatecboi4aq3jl4qv04mj36q0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          naver:
            client-id: UpEJjnGzwwLj_hk4mbB6
            client-secret: VLojXtDiDS
            scope:
              - id
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response