spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1001350064885-kms5egkoft11g0stgb1m8pg791c8c2fn.apps.googleusercontent.com
            client-secret: ENC(jUIXMoPhD9i1u1PcWTc9i0hvYlzMZikNpRqUp8gE2WV0mud4Rj+H74d85XAIW+e4)
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:3000/login/google"
          naver:
            client-id: UpEJjnGzwwLj_hk4mbB6
            client-secret: ENC(n9Zp2zZ17KdDJ0eL6Z1aY7knuXQBuIIX)
            scope:
              - id
              - email
              - nickname
            authorization-grant-type: authorization_code
            redirect-uri: "http://localshot:3000/login/naver"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
