spring:
  profiles:
    group:
      "local": "local, common, oauth"
    default: local
---
# common

spring:
  config:
    activate:
      on-profile: "common"
  # spring-starter-web 에서 페이지 mapping 안하기 위한 설정 (매핑되는 컨트롤러 없는 경우 401 에러 뜨는 걸 404로 바꾸기 위해 설정)
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

server:
  shutdown: graceful  # 서버 종료시 마지막 요청 처리 후 종료
  port: 8010
#  servlet:
#    session:
#      timeout: 2m
---
# local
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/neighborhooddb
      #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/neighborhooddb
      username: ENC(Oy+tIiSyGqRI+e/cIBvNpg==)
      password: ENC(DKleP4Bs7OkPNCiWCfvgNw==)
      minimum-idle: 10
      maximum-pool-size: 50

    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true
      log-level: info
      format-sql: true

  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true  # 쿼리 출력시 포맷 정렬
        use_sql_comments: true  # 주석 출력
        #show_sql: true  # JPA 출력시 쿼리 출력
        jdbc:
          time_zone: UTC

  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부(default: true)
      file-size-threshold: 0B # 파일이 디스크에 저장하지 않고 메모리에 저장하는 최소 크기(default: 0B)
      location: /neighborhood1/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 100MB  # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 100MB)


cloud:
  aws:
    s3:
      buket: ces-neighborhood
    credentials:
      access-key: ENC(4EpWW4esyg46rysYV68h3DXIlfVyBz0OMP+9BI6mLLw=)
      secret-key: ENC(Orm1WG6bUSNFUC3Ud92NhQgrCSv+4T5SxVjHmy78GZAFBmUQ17ZXHXn2rxokCStGy8nTklAvIiw=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

#logging:
#  level:
#    p6spy: info

#config: classpath:log4j2.xml

file:
  upload:
    image:
      server: /static/images/

jwt:
  header: Authorization
  secret: ENC(HfJqrC4QOfOtOYryrViTFTU/dn8+4rTuvgeJTzC0FlKdtJCZPH2ejtm3xEcb9jUPuu57QzSLyvQ=)
  issuer: neighborhood
  access-token-expire-time: 1800000
  refresh-token-expire-time: 120000
