------------------------------ DB생성 ------------------------------
CREATE USER master WITH PASSWORD '1234';

CREATE DATABASE neighborhoodb OWNER master;

GRANT ALL PRIVILEGES ON DATABASE neighborhoodb TO master;

------------------------------ 회원정보 ------------------------------
DROP TABLE IF EXISTS MBR_INFO CASCADE;

CREATE TABLE MBR_INFO
(
    MBR_ID    character varying(40) NOT NULL,
    MBR_PW    character varying(100),
    ROLE    character varying(30) NOT NULL,
    REFRESH_TOKEN    character varying(100),
    MBR_NICKNAME    character varying(20),
    MBR_PROFILE_IMAGE_URL    character varying(1000),
    MBR_STD    character varying(5),
    JOIN_DATE    timestamp,
    LAST_LOGIN_DATE    timestamp,
    WITHDRAW_DATE    timestamp,
    LOGIN_FAIL_CNT    smallint DEFAULT '0',
    MODIFY_DATE    timestamp
);

COMMENT ON COLUMN MBR_INFO.MBR_ID IS '회원 아이디';

COMMENT ON COLUMN MBR_INFO.MBR_PW IS '회원 비밀번호';

COMMENT ON COLUMN MBR_INFO.ROLE IS '권한';

COMMENT ON COLUMN MBR_INFO.REFRESH_TOKEN IS 'REFRESH_TOKEN';

COMMENT ON COLUMN MBR_INFO.MBR_NICKNAME IS '회원 별명';

COMMENT ON COLUMN MBR_INFO.MBR_PROFILE_IMAGE_URL IS '회원 프로필 주소';

COMMENT ON COLUMN MBR_INFO.MBR_STD IS '회원상태';

COMMENT ON COLUMN MBR_INFO.JOIN_DATE IS '가입일';

COMMENT ON COLUMN MBR_INFO.LAST_LOGIN_DATE IS '마지막 로그인 일자';

COMMENT ON COLUMN MBR_INFO.WITHDRAW_DATE IS '회원탈퇴 일자';

COMMENT ON COLUMN MBR_INFO.LOGIN_FAIL_CNT IS '로그인 실패 횟수';

COMMENT ON COLUMN MBR_INFO.MODIFY_DATE IS '수정일자';

COMMENT ON TABLE MBR_INFO IS '회원 정보';

CREATE UNIQUE INDEX MBR_INFO_PK ON MBR_INFO
( MBR_ID );

ALTER TABLE MBR_INFO
 ADD CONSTRAINT MBR_INFO_PK PRIMARY KEY 
 USING INDEX MBR_INFO_PK;

------------------------------ OAUTH 회원정보 ------------------------------
DROP TABLE IF EXISTS OAUTH_MBR_INFO CASCADE;

CREATE TABLE OAUTH_MBR_INFO
(
    OAUTH_ID    character varying(50) NOT NULL,
    PROVIDER    character varying(20) NOT NULL,
    OAUTH_NICKNAME    character varying(100),
    SNS_CONT_DATE    timestamp,
    MBR_ID    character varying(40) NOT NULL
);

COMMENT ON COLUMN OAUTH_MBR_INFO.OAUTH_ID IS 'OAUTH 아이디';

COMMENT ON COLUMN OAUTH_MBR_INFO.PROVIDER IS '제공자';

COMMENT ON COLUMN OAUTH_MBR_INFO.OAUTH_NICKNAME IS 'OAUTH 닉네임';

COMMENT ON COLUMN OAUTH_MBR_INFO.SNS_CONT_DATE IS 'SNS 연동일자';

COMMENT ON COLUMN OAUTH_MBR_INFO.MBR_ID IS '회원 아이디';

COMMENT ON TABLE OAUTH_MBR_INFO IS 'OAUTH 회원 정보';

CREATE UNIQUE INDEX SNS_MBR_INFO_PK ON OAUTH_MBR_INFO
( OAUTH_ID,PROVIDER );

ALTER TABLE OAUTH_MBR_INFO
 ADD CONSTRAINT SNS_MBR_INFO_PK PRIMARY KEY 
 USING INDEX SNS_MBR_INFO_PK;


------------------------------ 게시판 ------------------------------
DROP TABLE IF EXISTS BOARD CASCADE;

CREATE TABLE BOARD
(
    POST_NO    bigint NOT NULL,
    BOARD_TYPE    character varying(10),
    MBR_ID    character varying(40),
    TITLE    character varying(100),
    CONTENT    character varying(4000),
    DEL_YN    character varying(10),
    VIEW_CNT    integer DEFAULT '0',
    MODIFY_USER    character varying(40),
    MODIFY_DATE    timestamp,
    CREATE_USER    character varying(40) NOT NULL,
    CREATE_DATE    timestamp NOT NULL
);

COMMENT ON COLUMN BOARD.POST_NO IS '글 번호';

COMMENT ON COLUMN BOARD.BOARD_TYPE IS '글 유형';

COMMENT ON COLUMN BOARD.MBR_ID IS '회원 아이디';

COMMENT ON COLUMN BOARD.TITLE IS '제목';

COMMENT ON COLUMN BOARD.CONTENT IS '내용';

COMMENT ON COLUMN BOARD.DEL_YN IS '삭제여부';

COMMENT ON COLUMN BOARD.VIEW_CNT IS '조회수';

COMMENT ON COLUMN BOARD.MODIFY_USER IS '마지막수정자';

COMMENT ON COLUMN BOARD.MODIFY_DATE IS '마지막수정일자';

COMMENT ON COLUMN BOARD.CREATE_USER IS '최초생성자';

COMMENT ON COLUMN BOARD.CREATE_DATE IS '최초생성일자';

COMMENT ON TABLE BOARD IS '회원게시판';

CREATE UNIQUE INDEX BOARD_PK ON BOARD
( POST_NO );

ALTER TABLE BOARD
 ADD CONSTRAINT BOARD_PK PRIMARY KEY 
 USING INDEX BOARD_PK;

------------------------------ 댓글 ------------------------------
CREATE TABLE COMMENT
(
    COMMENT_NO    bigint NOT NULL,
    MBR_ID    character varying NOT NULL,
    CONTENT    character varying(4000),
    DEL_YN    character varying(10),
    MODIFY_USER    character varying(40),
    MODIFY_DATE    timestamp,
    CREATE_USER    character varying(40) NOT NULL,
    CREATE_DATE    timestamp NOT NULL,
    POST_NO    bigint
);

COMMENT ON COLUMN COMMENT.COMMENT_NO IS '댓글 번호';

COMMENT ON COLUMN COMMENT.MBR_ID IS '회원 아이디';

COMMENT ON COLUMN COMMENT.CONTENT IS '댓글 내용';

COMMENT ON COLUMN COMMENT.DEL_YN IS '삭제여부';

COMMENT ON COLUMN COMMENT.MODIFY_USER IS '마지막수정자';

COMMENT ON COLUMN COMMENT.MODIFY_DATE IS '마지막수정일자';

COMMENT ON COLUMN COMMENT.CREATE_USER IS '최초생성자';

COMMENT ON COLUMN COMMENT.CREATE_DATE IS '최초생성일자';

COMMENT ON COLUMN COMMENT.POST_NO IS '글 번호';

COMMENT ON TABLE COMMENT IS '댓글';

CREATE UNIQUE INDEX COMMENT_PK ON COMMENT
( COMMENT_NO );

ALTER TABLE COMMENT
 ADD CONSTRAINT COMMENT_PK PRIMARY KEY 
 USING INDEX COMMENT_PK;

------------------------------ 대댓글 ------------------------------
DROP TABLE IF EXISTS REPLY CASCADE;

CREATE TABLE REPLY
(
    REPLY_NO    bigint NOT NULL,
    MBR_ID    character varying NOT NULL,
    CONTENT    character varying(400),
    DEL_YN    character varying(10),
    MODIFY_USER    character varying(40),
    MODIFY_DATE    timestamp,
    CREATE_USER    character varying(40) NOT NULL,
    CREATE_DATE    timestamp NOT NULL,
    COMMENT_NO    bigint,
    POST_NO    bigint NOT NULL
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '대댓글 번호';

COMMENT ON COLUMN REPLY.MBR_ID IS '회원 아이디';

COMMENT ON COLUMN REPLY.CONTENT IS '대댓글 내용';

COMMENT ON COLUMN REPLY.DEL_YN IS '삭제여부';

COMMENT ON COLUMN REPLY.MODIFY_USER IS '마지막수정자';

COMMENT ON COLUMN REPLY.MODIFY_DATE IS '마지막수정일자';

COMMENT ON COLUMN REPLY.CREATE_USER IS '최초생성자';

COMMENT ON COLUMN REPLY.CREATE_DATE IS '최초생성일자';

COMMENT ON COLUMN REPLY.COMMENT_NO IS '댓글 번호';

COMMENT ON COLUMN REPLY.POST_NO IS '글 번호';

COMMENT ON TABLE REPLY IS '대댓글';

CREATE UNIQUE INDEX REPLY_PK ON REPLY
( REPLY_NO );

ALTER TABLE REPLY
 ADD CONSTRAINT REPLY_PK PRIMARY KEY 
 USING INDEX REPLY_PK;

------------------------------ 좋아요 ------------------------------
DROP TABLE IF EXISTS LIKES CASCADE;

CREATE TABLE LIKES
(
    POST_TYPE    character varying(10) NOT NULL,
    POST_NO    bigint NOT NULL,
    MBR_ID    character varying(40) NOT NULL,
    CREATE_DATE    timestamp NOT NULL
);

COMMENT ON COLUMN LIKES.POST_TYPE IS '글 종류';

COMMENT ON COLUMN LIKES.POST_NO IS '글 번호';

COMMENT ON COLUMN LIKES.MBR_ID IS '회원 아이디';

COMMENT ON COLUMN LIKES.CREATE_DATE IS '최초생성일자';

COMMENT ON TABLE LIKES IS '좋아요';

CREATE UNIQUE INDEX LIKES_PK ON LIKES
( POST_TYPE,POST_NO,MBR_ID );

ALTER TABLE LIKES
 ADD CONSTRAINT LIKES_PK PRIMARY KEY 
 USING INDEX LIKES_PK;

------------------------------ 공통코드 ------------------------------
DROP TABLE IF EXISTS CODE CASCADE;

CREATE TABLE CODE
(
    GRP_CD    character varying(10) NOT NULL,
    CD    character varying(10) NOT NULL,
    CD_NAME    character varying(200),
    USE_YN    character varying(1)
);

COMMENT ON COLUMN CODE.GRP_CD IS '그룹 코드';

COMMENT ON COLUMN CODE.CD IS '코드';

COMMENT ON COLUMN CODE.CD_NAME IS '코드명';

COMMENT ON COLUMN CODE.USE_YN IS '사용여부';

COMMENT ON TABLE CODE IS '코드';

CREATE UNIQUE INDEX UQ_CODE ON CODE
( GRP_CD,CD );

ALTER TABLE CODE
 ADD CONSTRAINT PK_CODE PRIMARY KEY 
 USING INDEX UQ_CODE;

------------------------------ 공통코드그룹 ------------------------------
DROP TABLE IF EXISTS CODE_GROUP CASCADE;

CREATE TABLE CODE_GROUP
(
    GRP_NM    character varying(200),
    USE_YN    character varying(1),
    GRP_CD    character varying(10) NOT NULL
);

COMMENT ON COLUMN CODE_GROUP.GRP_NM IS '그룹명';

COMMENT ON COLUMN CODE_GROUP.USE_YN IS '사용여부';

COMMENT ON COLUMN CODE_GROUP.GRP_CD IS '그룹 코드';

COMMENT ON TABLE CODE_GROUP IS '그룹';

CREATE UNIQUE INDEX UQ_CODE_GRP ON CODE_GROUP
( GRP_CD );

ALTER TABLE CODE_GROUP
 ADD CONSTRAINT PK_CODE_GROUP PRIMARY KEY 
 USING INDEX UQ_CODE_GRP;


DROP TABLE IF EXISTS COMMENT CASCADE;
