PORT: 8010
# Spring
spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ENC(AQnYRndp9XxQL60oG32dX7tsShCInt1n2OP1SGoGd71mbjdKn/iXZGf3yxqF90487dQd9blIb4H4Qeh8Ce7f4qr7ZALuW4Y/)
      username: ENC(e/KE2yOzAi1r7yEuNCspnA==)
      password: ENC(Agl4h4nz+O2d8bNbqRkziruQChA6yulF)

server:
  shutdown: graceful
