PORT: 8010
# Spring
spring:
  datasource:
    hikari:
      #jdbc-url: neighborhood-db.crngyweqerpj.us-east-2.rds.amazonaws.com:5432
      driver-class-name: org.postgresql.Driver
      jdbc-url: ENC(AQnYRndp9XxQL60oG32dX7tsShCInt1n2OP1SGoGd71mbjdKn/iXZGf3yxqF90487dQd9blIb4H4Qeh8Ce7f4qr7ZALuW4Y/)
      username: ENC(e/KE2yOzAi1r7yEuNCspnA==)
      password: ENC(Agl4h4nz+O2d8bNbqRkziruQChA6yulF)

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1001350064885-a7tp24je0net5ktb46tlgeji2t8jhtdc.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

server:
  shutdown: graceful
